// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH6tPMg0H5mA4OUQtjQTZhrTc0Y0BzaL8',
    appId: '1:98255824763:web:bccb46212981f56ef0ffde',
    messagingSenderId: '98255824763',
    projectId: 'learning-app-1d288',
    authDomain: 'learning-app-1d288.firebaseapp.com',
    storageBucket: 'learning-app-1d288.firebasestorage.app',
    measurementId: 'G-6X2273RQEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyjLW660xbUSIl7M6PTR6aU_ZBoXUgiRg',
    appId: '1:98255824763:android:56e58e3481bf4cc4f0ffde',
    messagingSenderId: '98255824763',
    projectId: 'learning-app-1d288',
    storageBucket: 'learning-app-1d288.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHg9P-ZcylWd-IOWMsJvGeCaP3lYqakjE',
    appId: '1:98255824763:ios:f70b4d70a0f228d7f0ffde',
    messagingSenderId: '98255824763',
    projectId: 'learning-app-1d288',
    storageBucket: 'learning-app-1d288.firebasestorage.app',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHg9P-ZcylWd-IOWMsJvGeCaP3lYqakjE',
    appId: '1:98255824763:ios:f70b4d70a0f228d7f0ffde',
    messagingSenderId: '98255824763',
    projectId: 'learning-app-1d288',
    storageBucket: 'learning-app-1d288.firebasestorage.app',
    iosBundleId: 'com.example.learningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH6tPMg0H5mA4OUQtjQTZhrTc0Y0BzaL8',
    appId: '1:98255824763:web:365bf7c1567a1c05f0ffde',
    messagingSenderId: '98255824763',
    projectId: 'learning-app-1d288',
    authDomain: 'learning-app-1d288.firebaseapp.com',
    storageBucket: 'learning-app-1d288.firebasestorage.app',
    measurementId: 'G-8G2HNTM6DW',
  );
}
